FROM ollama/ollama:latest

# コンテナ起動後に以下を手動実行する
# ollama pull hf.co/unsloth/DeepSeek-R1-Distill-Llama-8B-GGUF:latest
# ollama pull hf.co/mmnga/cyberagent-DeepSeek-R1-Distill-Qwen-14B-Japanese-gguf:latest
# ollama pull hf.co/mmnga/cyberagent-DeepSeek-R1-Distill-Qwen-32B-Japanese-gguf:latest
# ollama pull deepseek-coder:latest
# ollama pull hf.co/TheBloke/deepseek-coder-6.7B-instruct-GGUF:deepseek-coder-6.7b-instruct.Q4_K_M.gguf