version: '3.8'

volumes:
  postgres-data:
  ollama:
   driver_opts:
    o: 'size=100G'

services:
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye
    # コンテナの名前を指定します。
    container_name: app_container
    # GPUサポートの追加
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD}
    # env_file:
    #     # Ensure that the variables in .env match the same variables in devcontainer.json
    #     - ../.env.local
    volumes:
      - ../:/WorkTimeManagementV2:cached 
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    networks: 
      - worktime-management-network
    depends_on:
      - db
      - ollama
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    # コンテナの名前を指定します。
    container_name: db_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD}
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    # ports:
      # - 5432:5432
      # - 3000:3000
    networks: 
      - worktime-management-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    # env_file:
    #   # Ensure that the variables in .env match the same variables in devcontainer.json
    #   - .env.db
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    container_name: ollama_container
    networks: 
      - worktime-management-network
    volumes:
      - ollama:/root/.ollama:cached
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped

networks:
  worktime-management-network:
    driver: bridge